/**
 * NoraCivilis v3 — Self-Expansion Engine
 * Creates new modules, files, or structures based on evolutionary suggestions
 */

const fs = require('fs');

class ExpansionEngine {

  expand(memory) {
    const events = memory.events || [];
    const expansions = [];

    // آخرین پیشنهاد فرگشتی را پیدا کن
    const lastEvolution = events
      .filter(e => e.evolution)
      .slice(-1)[0];

    if (!lastEvolution || !lastEvolution.evolution) {
      return { status: "no_evolution_data" };
    }

    const suggestions = lastEvolution.evolution.suggestions || [];

    for (const suggestion of suggestions) {

      // 1) اگر پیشنهاد افزایش پیچیدگی بود → ساخت یک ماژول جدید
      if (suggestion.type === "complexity_increase") {
        const path = "/nora-v3/modules/auto-generated-module.js";

        try {
          fs.mkdirSync("/nora-v3/modules", { recursive: true });
          fs.writeFileSync(path,
            `// Auto-generated by Nora v3 Expansion Engine\nmodule.exports = { status: "active" };`
          );

          expansions.push({
            type: "module_created",
            path,
            message: "New module created due to system stability"
          });

        } catch (err) {
          expansions.push({
            type: "error",
            message: err.message
          });
        }
      }

      // 2) اگر پیشنهاد قانون دائمی بود → ساخت فایل rule جدید
      if (suggestion.type === "permanent_rule") {
        const path = "/nora-v3/rules/auto-rule.json";

        try {
          fs.mkdirSync("/nora-v3/rules", { recursive: true });
          fs.writeFileSync(path, JSON.stringify({
            rule: "auto_generated_corruption_prevention",
            files: suggestion.files || [],
            createdAt: Date.now()
          }, null, 2));

          expansions.push({
            type: "rule_created",
            path,
            message: "Permanent rule created for corruption prevention"
          });

        } catch (err) {
          expansions.push({
            type: "error",
            message: err.message
          });
        }
      }

      // 3) اگر پیشنهاد تغییر ساختار بود → ساخت یک فایل ساختاری جدید
      if (suggestion.type === "structural_change") {
        const path = "/nora-v3/structure/auto-structure.txt";

        try {
          fs.mkdirSync("/nora-v3/structure", { recursive: true });
          fs.writeFileSync(path,
            `Auto structural suggestion: ${suggestion.message}`
          );

          expansions.push({
            type: "structure_created",
            path,
            message: "New structural file created"
          });

        } catch (err) {
          expansions.push({
            type: "error",
            message: err.message
          });
        }
      }
    }

    return {
      status: "expanded",
      expansions
    };
  }
}

module.exports = new ExpansionEngine();
